version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/data"
    schedule:
      interval: "daily"
    ignore:
      update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
