apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    url: ${CrateDBHost}:5432
    user: ${CrateDBUser}
    database: ${CrateDBDatabase}
    isDefault: true
    editable: false

    # Password goes in secureJsonData
    secureJsonData:
      password: ${CrateDBPass}

    # Postgres-specific options
    jsonData:
      sslmode: require