{
 "title": "CrateDB Real Time Demo (Munich)",
 "time": { "from": "2025-08-10T00:00:00.000Z", "to": "2025-08-16T23:59:59.000Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  latitude(geo_location) as latitude,\n  longitude(geo_location) as longitude,\n  data['temperature'] as temperature\nFROM\n  demo.climate_data\n  WHERE $__timeFilter(\"timestamp\")\n  AND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)\n  ORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  latitude(geo_location) as latitude,\n  longitude(geo_location) as longitude,\n  data['pressure'] as pressure\nFROM\n  demo.climate_data\n  WHERE $__timeFilter(\"timestamp\")\nAND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)  ORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  latitude(geo_location) as latitude,\n  longitude(geo_location) as longitude,\n sqrt(data['u10']*data['u10'] + data['v10']*data['v10']) AS wind_speed\n FROM\n  demo.climate_data\n  WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\n  AND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)\n  ORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Min/max/avg temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  min(data['temperature']) as \"min\",\n  max(data['temperature']) as \"max\",\n  avg(data['temperature']) as \"avg\"\nFROM\n  demo.climate_data\n  WHERE $__timeFilter(\"timestamp\")\n  AND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)  \nGROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Min/max/avg pressures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  min(data['pressure']) as \"min\",\n  max(data['pressure']) as \"max\",\n  avg(data['pressure']) as \"avg\"\nFROM\n  demo.climate_data\n  WHERE $__timeFilter(\"timestamp\")\n  AND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)\n  GROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Min/max/avg wind speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  min(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS \"min\",\n  max(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS \"max\",\n  avg(sqrt(data['u10']*data['u10'] + data['v10']*data['v10'])) AS \"avg\"\nFROM\n  demo.climate_data\n  WHERE $__timeFilter(\"timestamp\")\n    AND within(\n  geo_location,\n  'POLYGON((\n    11.576 48.587,\n    11.829 48.569,\n    12.060 48.518,\n    12.259 48.435,\n    12.417 48.325,\n    12.528 48.193,\n    12.586 48.047,\n    12.586 47.887,\n    12.528 47.741,\n    12.417 47.609,\n    12.259 47.499,\n    12.060 47.416,\n    11.829 47.365,\n    11.576 47.347,\n    11.323 47.365,\n    11.092 47.416,\n    10.893 47.499,\n    10.735 47.609,\n    10.624 47.741,\n    10.566 47.887,\n    10.566 48.047,\n    10.624 48.193,\n    10.735 48.325,\n    10.893 48.435,\n    11.092 48.518,\n    11.323 48.569,\n    11.576 48.587\n  ))'\n)\n  GROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  }
 ]
}