{
 "title": "CrateDB Real Time Demo",
 "time": { "from": "2025-08-09T00:00:00.000Z", "to": "2025-08-16T23:59:59.000Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  LATITUDE(geo_location) as latitude,\n  LONGITUDE(geo_location) as longitude,\n  data['temperature'] as temperature\nFROM\n  demo.climate_data\nWHERE $__timeFilter(\"timestamp\")\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  LATITUDE(geo_location) as latitude,\n  LONGITUDE(geo_location) as longitude,\n  data['pressure'] as pressure\nFROM\n  demo.climate_data\nWHERE $__timeFilter(\"timestamp\")\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as time,\n  latitude(geo_location) as latitude,\n  longitude(geo_location) as longitude,\n  SQRT(data['u10'] * data['u10'] + data['v10'] * data['v10']) AS wind_speed\n FROM\n  demo.climate_data\nWHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY timestamp;\n"
    }
   ]
  },
  {
   "title": "Min/max/avg temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  MIN(data['temperature']) as \"min\",\n  MAX(data['temperature']) as \"max\",\n  AVG(data['temperature']) as \"avg\"\nFROM\n  demo.climate_data\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Min/max/avg pressures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  MIN(data['pressure']) as \"min\",\n  MAX(data['pressure']) as \"max\",\n  AVG(data['pressure']) as \"avg\"\nFROM\n  demo.climate_data\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Min/max/avg wind speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "dataset": "crate",
     "rawSql": "SELECT\n  timestamp as ts,\n  MIN(SQRT(data['u10'] * data['u10'] + data['v10'] * data['v10'])) AS \"min\",\n  MAX(SQRT(data['u10'] * data['u10'] + data['v10'] * data['v10'])) AS \"max\",\n  AVG(SQRT(data['u10'] * data['u10'] + data['v10'] * data['v10'])) AS \"avg\"\nFROM\n  demo.climate_data\nWHERE $__timeFilter(\"timestamp\")\nGROUP BY timestamp\nORDER BY timestamp;"
    }
   ]
  }
 ]
}